# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LoadShapefilePlugin
                                 A QGIS plugin
 to load shapefile and visulise
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-11
        copyright            : (C) 2025 by Apurwa Chaurasia
        email                : apurwa2776@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LoadShapefilePlugin class from file LoadShapefilePlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .LoadShapefilePlugin import LoadShapefilePlugin
    return LoadShapefilePlugin(iface)
